

CREATE ROLE admin;


GRANT gerente TO admin;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO admin;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO admin;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO admin;
